# Generated by Django 3.0.4 on 2020-04-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiBasics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articals',
            new_name='Articles',
        ),
    ]
